# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wii Create
shortname:      Wii Create
company:        Ark Ng
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Branded merch for employees, customers or events 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
charset:        'UTF-8'
timezone:       Africa/Lagos

# Build settings
markdown: kramdown
theme: minima
# permalink:      pretty

# Collections
collections:
  categories:
    title:  Categories
    # output: true
  products:
    title:  Products
    # output: true
  packs:
    title:  Packs
    output: true

#Defaults
defaults:
  # - scope:
  #     type: products
  #   values:
  #     layout: product-single
  #     permalink: /products/:path
  - scope:
      type: packs
    values:
      layout: product-single
      permalink: /products/:path

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# Handling Sass
sass:
  sass_dir: _sass
  # style: compressed

include:
  - _pages
  - _checkout

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
